### ISSUE TITLE
Needs server.cfg completed

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/gamesvr-hldms-freeplay#1]
- [x] MOTD

- [x] Fast Downloads (`fastDownloads/hldms/*`)

- [x] Hostname

- [x] High bandwidth

- [x] rcon banning

**Comment by JustinBenedick** [comment]
Done in a pull request. 

Also motd is set to http://content.lacledeslan.net/motd/hldms-generic.html
that still need to be made
